In [2]:
import numpy as np

In [74]:
def computeLinearReg(X,y,theta,alpha):
    [m,n]=X.shape
    H=np.dot(X,theta)
    error=H-y
    J=(1/(2*m))*sum(np.multiply(error,error))#cost
    grad=np.multiply((alpha/m),(np.dot(X.T,error)))
    return [J,grad]

In [92]:
def feature_generator(X,degree):
    x1=X[:,0]#m *1
    x2=X[:,1]#m*1
    out=np.ones([X.shape[0],1])#m*n
    for i in range(1,degree+1):
        for j in range(0,i+1):
            temp=np.multiply(np.power(x1,i-j),np.power(x2,j))
            #print(temp.shape)
            #print(out.shape)
            out=np.append(out,temp.reshape(-1,1),axis=1)
    return out

In [58]:
def gradient_descent(X,y,theta,alpha,num_iterations):
    J_history=np.zeros([num_iterations,1])
    for i in range(num_iterations):
        a=computeLinearReg(X,y,theta,alpha)
        J_history=a[0]
        grad=a[1]
        theta=theta-grad
    return theta

In [110]:
def polynomial_regression(X_train,y,theta,alpha,degree,X_test,num_iterations):
    X=X_train
    [m,n]=X.shape
    X_mod=feature_generator(X,degree)#m*some number
    theta=np.random.randn(X_mod.shape[1],1)
    theta=gradient_descent(X_mod,y,theta,alpha,num_iterations)#n+1 * 1
    #temp=np.ones([X.shape[0],1])
    X_test=feature_generator(X_test,degree)
    #X_test=np.append(temp,X_test,axis=1)
    predict=np.dot(X_test,theta)
    return predict

In [89]:
a=np.array([[1,2,3],[3,4,5]])
[m,n]=a.shape
a.T
b=[[10],[11]]
a=np.append(b,a,axis=1)
c=[[2],[3]]
print(a)

[[10  1  2  3]
 [11  3  4  5]]


In [100]:
X=np.array([[1,2],[3,4]])
y=[[8],[19]]
theta=[[0],[0],[0]]

#a=computeLinearReg(X,y,theta,0.1)
#print(gradient_descent(X,y,theta,0.1,10))

In [101]:
print(feature_generator(np.array([[1,2],[3,4]]),1))

[[1. 1. 2.]
 [1. 3. 4.]]


In [113]:
print(polynomial_regression(X,y,theta,0.1,1,X,10))

[[ 8.51184389]
 [18.61559059]]
